### PR TITLE
replace 'yihui/hugo-lithium-theme' with 'yihui/hugo-lithium'

### PR DESCRIPTION
**Pull request by rorynolan**
When I run `blogdown::new_site()` with the default `theme = "yihui/hugo-lithium-theme"`, I get an error:
```
Rendering content/post/2015-07-23-r-rmarkdown.Rmd
Error: Unable to find theme Directory: /Users/rnolan/Dropbox/R/blog/themes/hugo-lithium-theme

Serving the directory /Users/rnolan/Dropbox/R/blog at http://127.0.0.1:5641
To stop the server, run servr::daemon_stop("4326078320") or restart your R session
Error in setwd(site.dir) : cannot change working directory
```
However I notice that even though there's no `/Users/rnolan/Dropbox/R/blog/themes/hugo-lithium-theme`, there is a `/Users/rnolan/Dropbox/R/blog/themes/hugo-lithium`. For reasons that I don't fully understand, when I run `blogdown::new_site(theme = "yihui/hugo-lithium")`, everything works fine. This may be because https://github.com/yihui/hugo-lithium-theme redirects to https://github.com/yihui/hugo-lithium, but I don't know. In any case, https://github.com/yihui/hugo-lithium seems to be in working order and I think it should all work fine with that as the new default.
Thanks Yihui and other authors and maintainers, your work makes our lives easier :)

### CODE REVIEW

**Comment by rorynolan** [comment]
Oops, hang on, some CI errors there that I think I can fix. Trying now.

**Comment by yihui** [comment]
Ah. My bad. Thanks a lot for catching this issue!

**Comment by yihui** [comment]
I see you are tweaking the Rd file. If you `install.packages("Rd2roxygen")`, and use the button `Install and Restart` in RStudio, you will get my style. Thanks!

**Comment by rorynolan** [comment]
Hi @yihui, there are also a few places in the blogdown book where "hugo-lithium-theme" needs to be changed to "hugo-lithium". Would you also like a PR to fix these?

**Comment by yihui** [comment]
@rorynolan Thanks! I have already changed them in the book in the commit 8ba2460 (I amended your PR).

**Comment by rorynolan** [comment]
OK great work. Thanks for everything!

**Pull request merged**
