### PR TITLE
Build site from only modified .Rmd files

### PR DESCRIPTION
**Pull request by RobertMyles**
Very simple wrapper around 

```
blogdown::build_site(local = TRUE, run_hugo = FALSE)
blogdown::hugo_build()
```

to avoid the case where blogdown automatically compiles all .Rmd files in the website directory, which can often cause problems with code from an earlier date that does not run anymore for whatever reason (i.e. website scraping code that fails because the website has changed). Kept it simple to avoid messing around with the rest of the blogdown code.

See [this](https://stackoverflow.com/questions/46470197/clarity-on-publishing-drafts-with-blogdown) SO question for context.

### CODE REVIEW

**Comment by RobertMyles** [comment]
I do use Netlify, and using `serve_site()` in this way builds draft posts, which are not ready for publication. Since I'd rather not go through two separate steps (see your answer on the SO link), I thought one would be better. What do you recommend for avoiding ding this in two steps, Yihui?

**Comment by yihui** [comment]
You don't need two steps. `serve_site()` plus `git push` is all you need. Just let Netlify build your site for you on the cloud using Hugo: https://bookdown.org/yihui/blogdown/netlify.html (which will not build draft posts)

**Comment by RobertMyles** [comment]
That has never worked for me without building drafts, but it must be something buggy on my end. Ok, thanks, and sorry for taking up your time with this (again!).

**Comment by yihui** [comment]
No worries. Hugo does not build drafts by default, so you can specify `hugo`as the build command, a proper `HUGO_VERSION`, and `public` as the publish directory. If it does not work, there may be something wrong in your Netlify settings.

**Pull request closed without merging**
