### PR TITLE
typo

### PR DESCRIPTION
**Pull request by daijiang**

### CODE REVIEW

**Comment by daijiang** [comment]
Okay, another small thing: in your personal experience, you wrote "140 words may well be thoughtful...". Will it be 140 characters? (I know I am too picky)

**Comment by yihui** [comment]
You are correct. I just corrected it. Thanks!

**Comment by daijiang** [comment]
Since we already started this, can you actually put a link to your Perl regular expression in your personal experience appendix for readers? I probably can find it, but it would be great not to.

I just finished reading your book. Great work!

**Comment by daijiang** [comment]
I see why there is no link now. So, never mind. 😄

**Pull request merged**
