### PR TITLE
Add pandoc as prerequisite

### PR DESCRIPTION
**Pull request by m4xl1n**

### CODE REVIEW

**Comment by yihui** [comment]
Thanks! Pandoc is included in RStudio, so it does not have to be installed separately.

**Comment by m4xl1n** [comment]
I didn't installed RStudio before I installed blogdown, and that's why I found the missing pandoc dependency.

Do we think blowdown can be still used by those who do not necessarily install RStudio?

**Comment by yihui** [comment]
If RStudio is not installed, Pandoc has to be installed, and blogdown is not tied to RStudio (you can use any editors). Yes, this should be clarified. Could you update this PR to clarify it? Thanks!

**Comment by m4xl1n** [comment]
I add few words to clarify the pandoc dependency only comes when RStudio is not installed. Please take another look.

**Pull request merged**
