### PR TITLE
Checks

### PR DESCRIPTION
**Pull request by apreshill**
I am starting with `check_config()`. Additional improvements would be to use `switch` for all the messages so YAML vs TOML is shown correctly. But wanted to share where I am at now for feedback!

An example with `[TODO]` items:
```
> blogdown::check_config()
― Checking config.yaml
| Checking 'baseURL' setting for Hugo...
| Found 'baseURL = /'
● [TODO] Update 'baseURL' to your actual URL when ready to publish. 
| Checking 'ignoreFiles' setting for Hugo...
● [TODO] Remove '_files$' from 'ignoreFiles': 
  "\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$" 
| Checking setting for Hugo's markdown renderer...
| You are using the 'goldmark' markdown renderer.
● [TODO] Allow goldmark to render raw HTML by adding this setting to config.yaml :
 
markup:
  goldmark:
    renderer:
      unsafe: true
 
==> Do you want blogdown to set this for you? (y/n) n
― Check complete: config.yaml
```

A clean check:
```
> blogdown::check_config()
― Checking config.yaml
| Checking 'baseURL' setting for Hugo...
| Found 'baseURL = https://alison.rbind.io'
○ 'baseURL' set- nothing to do here! 
| Checking 'ignoreFiles' setting for Hugo...
○ Found all recommended 'ignoreFiles': 
  "\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$" 
| Checking setting for Hugo's markdown renderer...
○ All set! Found 'unsafe' setting - Hugo will render raw HTML. 
― Check complete: config.yaml
```

Additional `[TODO]` item after this is done is to make `check_site(collect_todos = TRUE)` work, so that all the `[TODO]` items can be combined/printed out together instead of staggered. I think @cderv had ideas about how to do that.

### CODE REVIEW

**Comment by apreshill** [comment]
For `check_gitignore()`

Work to be done
```
> blogdown::check_gitignore()
― Checking .gitignore
| Checking for items you can safely ignore...
● [TODO] You can safely add to .gitignore : blogdown, .DS_Store, Thumbs.db 
| Checking for items to remove...
● [TODO] Remove items from .gitignore : *.md, *.html 
| Checking for items to ignore if Netlify builds your site...
● [TODO] With Netlify building your site, you can safely add to .gitignore : public, resources 
― Check complete: .gitignore
```

A clean check
```
> blogdown::check_gitignore()
― Checking .gitignore
| Checking for items you can safely ignore...
○ Found! You have safely ignored: blogdown, .DS_Store, Thumbs.db 
| Checking for items to remove...
○ Nothing to see here - found no items to remove. 
| Checking for items to ignore if Netlify builds your site...
○ Found! You have safely ignored: public 
● [TODO] You can safely add to .gitignore : resources 
― Check complete: .gitignore
```

**Review by yihui — COMMENTED** [review]
Looks like a good start! Thanks!

> I would like to mute the chunk that starts with "— Found hugo" but cannot figure out how to do that.

I'll take care of that.

**Comment by apreshill** [comment]
`check_hugo()` progress:

# no Hugo version set in .Rprofile
```
> blogdown::check_hugo()
― Checking Hugo
| Checking Hugo version...

==> Found hugo at "/Users/alison/Library/Application Support/Hugo/0.78.2/hugo" and "/usr/local/bin/hugo". The former will be used. If you don't need both copies, you may delete/uninstall the latter.

○ Found! You are using Hugo 0.78.2.
| Checking .Rprofile for Hugo version used by blogdown...
| Hugo version not set in .Rprofile.
● [TODO] Use blogdown::config_Rprofile() to create project .Rprofile.
● [TODO] Set options(blogdown.hugo.version = "0.78.2") to use current Hugo version.
```

(again, would love to suppress the "Found hugo..." message)

# set + latest Hugo installed

```
> blogdown::check_hugo()
― Checking Hugo
| Checking Hugo version...

==> Found hugo at "/Users/alison/Library/Application Support/Hugo/0.78.2/hugo" and "/usr/local/bin/hugo". The former will be used. If you don't need both copies, you may delete/uninstall the latter.

○ Found Hugo! You are using Hugo 0.78.2.
| Checking .Rprofile for Hugo version used by blogdown...
○ Blogdown is using Hugo 0.78.2 to build site locally.
| Checking for more recently installed Hugo versions...
○ Blogdown is using the most up-to-date Hugo version installed (0.78.2) to build site locally.
```

# set + not the latest Hugo installed
```
> blogdown::check_hugo()
― Checking Hugo
| Checking Hugo version...

==> Found hugo at "/Users/alison/Library/Application Support/Hugo/0.71.1/hugo" and "/usr/local/bin/hugo". The former will be used. If you don't need both copies, you may delete/uninstall the latter.

○ Found Hugo! You are using Hugo 0.71.1.
| Checking .Rprofile for Hugo version used by blogdown...
○ Blogdown is using Hugo 0.71.1 to build site locally.
| Checking for more recently installed Hugo versions...
| Found Hugo version 0.71.1 in .Rprofile, but version 0.78.2 is more recent.
● [TODO] Set options(blogdown.hugo.version = "0.78.2") to use newest installed Hugo version.
```


# TO DO

I ran into errors with the scenario of "I set my Hugo version in .Rprofile as a version I don't have installed locally" Any pointers for debugging would be much appreciated!

**Comment by yihui** [comment]
> (again, would love to suppress the "Found hugo..." message)

With the latest `master` branch (you need to pull to your `master` branch and merge your `checks` branch with `master`), `find_hugo(quiet = TRUE)` will suppress this message.

> I ran into errors with the scenario of "I set my Hugo version in .Rprofile as a version I don't have installed locally" Any pointers for debugging would be much appreciated!

You can `tryCatch(find_hugo(version), error = function(e) NULL)` to avoid the error, but (1) I wonder how likely users are to run into this problem; (2) the error message is probably clear enough for them to know what to do next (it will tell them to `blogdown::install_hugo(version)`). Before they run `check_hugo()`, they are most likely to have already run into this error if they have tried to serve or build the site. This is a fundamental error that they definitely should fix before they could do anything, so I feel it doesn't belong to the diagnostics (to me, diagnostics are mostly for "gotchas"). That said, I'm open to supporting this anyway.

**Comment by apreshill** [comment]
@yihui thank you! And yes I agree re: diagnostics versus errors. It doesn't look like `quiet=TRUE` works as an arg for `hugo_available()`, which is where I think some of these messages originate from

**Comment by yihui** [comment]
I just added `quiet = TRUE` to these functions. Thanks!

**Comment by apreshill** [comment]
@yihui I don't see in the commit history the change to `hugo_available()`:

```
> blogdown::check_config()
― Checking config.toml
| Checking "baseURL" setting for Hugo...
| Found "baseURL = /"
● [TODO] Update "baseURL" to your actual URL when ready to publish.
| Checking "ignoreFiles" setting for Hugo...
○ Found all recommended "ignoreFiles":
"\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"
| Checking setting for Hugo markdown renderer...
Error in hugo_available("0.60", quiet = TRUE) : 
  unused argument (quiet = TRUE)
```

**Comment by yihui** [comment]
Sorry, I meant I added `quiet = TRUE` to `hugo_version()` internally (b860d27fb475eeb7401fbc0542d46962eeac17b7), so `hugo_version()` won't generate the message anymore.

**Comment by apreshill** [comment]
I got it and works beautifully- thank you!

**Comment by apreshill** [comment]
Moving onto `check_netlify()`

Some to do items:
```
> blogdown::check_netlify()
― Checking netlify.toml...
| Checking HUGO_VERSION setting in netlify.toml...
○ Found HUGO_VERSION = 0.78.2 in netlify.toml.
| Checking that Netlify & local Hugo versions match...
| Mismatch found:
| blogdown is using Hugo version (0.71.1) to build site locally.
| Netlify is using Hugo version (0.78.2) to build site.
● [TODO] Option 1: Change HUGO_VERSION = 0.71.1 in netlify.toml to match local version.
● [TODO] Option 2: Use blogdown::install_hugo("0.78.2") to match Netlify version.
● [TODO] If Option 2: Set options(blogdown.hugo.version = "0.78.2") in .Rprofile to pin this Hugo version.
| Checking that Netlify & local Hugo publish directories match...
○ You are good to go! Blogdown and Netlify are using the same publish directory (public).
― Check complete: netlify.toml
```

Clean check:
```
> blogdown::check_netlify()
― Checking netlify.toml...
| Checking HUGO_VERSION setting in netlify.toml...
○ Found HUGO_VERSION = 0.78.2 in netlify.toml.
| Checking that Netlify & local Hugo versions match...
○ It's a match! Blogdown and Netlify are using the same Hugo version (0.78.2).
| Checking that Netlify & local Hugo publish directories match...
○ You are good to go! Blogdown and Netlify are using the same publish directory (public).
― Check complete: netlify.toml
```

**Comment by apreshill** [comment]
Hi @yihui and @cderv -

Thanks for the assists with revising these checking functions. I think they are ready for your review.

**Review by yihui — APPROVED** [review]
Looks fantastic to me! If you don't mind, I'll make some cosmetic changes (mostly about white spaces) and merge this PR. Thank you very much!

**Comment by apreshill** [comment]
Please do, thanks!

**Comment by yihui** [comment]
Great! I'll carry on from here.

**Comment by apreshill** [comment]
@yihui in testing, just noticed that if I ask for an uninstalled Hugo version in `.Rprofile` I see this:

```
> blogdown::hugo_version()
Error: Found 'hugo' at '/usr/local/bin/hugo' but its version is 0.75.1 instead of the requested version 0.76.1. You may try blogdown::install_hugo("0.76.1").
Called from: find_exec("hugo", "Hugo", version, c("You may try blogdown::install_hugo(", 
    sprintf("\"%s\"", version), ")."), quiet)
Browse[1]> 
```

I don't see that with the dev version currently, but I didn't touch that function so now sure why I'm seeing this error here.

**Comment by yihui** [comment]
If you have `options(blogdown.hugo.version = '0.76.1')` in `.Rprofile` but have uninstalled this version, the current dev version should signal the same error. I don't think this PR changed anything relevant to that.

**Comment by apreshill** [comment]
Well, with the dev version, I get an error but not the prompt to browse:

```
> blogdown::hugo_version()
Error: Found 'hugo' at '/usr/local/bin/hugo' but its version is 0.75.1 instead of the requested version 0.76.1. You may try blogdown::install_hugo("0.76.1").
```

**Comment by yihui** [comment]
The browse prompt was probably because you accidently clicked on the left of a line number and added a breakpoint in the IDE like this:

**Comment by apreshill** [comment]
oh wow- thank goodness- I'm so glad I didn't break anything else!! Thank you 🥇

**Review by yihui — APPROVED** [review]
@apreshill I just finished tweaking the PR, and want to verify with you if these two commits are okay with you:

- [ ] 224aea1a42f32252025315cb9c1754ce4ee35871 Is that what you meant?
- [ ] 21db26000e1c9dfdc7c20d5e9e1a02dea703ad89 Perhaps we should not recommend updating Hugo?

This PR was a lot of work! Thank you so much!

**Comment by apreshill** [comment]
Thanks for the update. Yes those both look OK to me. For updating Hugo, my main reservation is the use case we observed in our session last Friday, where someone in the same session installed a newer version of Hugo (I believe Tom started his site with v.15 for example)- so it is possible they updated it without realizing that it is "frozen" for the project and may be confused why their update doesn't seem to take effect. This is beyond what I can offer, but to catch that very predictable pitfall, perhaps we could offer the prompt if we detect that the installed version was installed in the same work session? Or we could intercept at the `install_hugo()` stage if they have an existing installation and give a gentle nudge like "You just installed a more recent version of Hugo (xxx), but this project is using version YYY. blah blah blah." What do you think? I'm fine with the changes as is though!

**Comment by yihui** [comment]
I see. Thanks for the explanation!

> Or we could intercept at the `install_hugo()` stage if they have an existing installation and give a gentle nudge like "You just installed a more recent version of Hugo (xxx), but this project is using version YYY set in your .Rprofile. blah blah blah."

I'll do that in `install_hugo()`, since we've already done this: https://github.com/rstudio/blogdown/blob/b860d27fb475eeb7401fbc0542d46962eeac17b7/R/install.R#L156-L163

**Comment by yihui** [comment]
I just realized that I had already done it last month: https://github.com/rstudio/blogdown/blob/130ff879efacbef900779a94b96de0880fb662aa/R/install.R#L76-L80
Not sure why Tom missed the message when installing a newer version of Hugo.

**Pull request merged**
