### PR TITLE
Allow to select config format in new project menu

### LINKED ISSUE #606: No config.toml
When I create a new project with "Website using blogdown", there is a possibility to remove "convert all metadata to yaml". Then there is no config.toml. Instead there is a config.yaml.

### PR DESCRIPTION
**Pull request by cderv**
This add a selector menu for choosing config format
image

closes #606

### CODE REVIEW

**Review by apreshill — APPROVED** [review]
Yes! Thank you 👍

**Comment by cderv** [comment]
I get one approval, I'll merge ! 😄 

@yihui you can tweak later if needed.

**Review by yihui — COMMENTED** [review]
That's great! I'll probably tweak the order of all these options later. Thanks!

**Comment by cderv** [comment]
I tried several layout of them and decided it was interesting to have this option just above the one regarding YAML metadata so that you don't confuse the two. 

However the SelectInput creates a space below that makes it a bit weird. 

happy tweaking !

**Comment by yihui** [comment]
How does this version look to you?

image

**Comment by cderv** [comment]
It is better without the select input. Nice idea to have also allow TRUE / FALSE in `new_site()` !

**Comment by apreshill** [comment]
If I saw this, I'm not sure I'd know what to do. Could we make it more clear what the alternative is? (i.e., if all I know is YAML, sure this sounds great!) Maybe the reword could be "convert config file to YAML automatically (if TOML, comments will be removed)"?

**Comment by yihui** [comment]
> convert config file to YAML

Good suggestion! Will do in a second.

> (if config.toml file is found, comments are removed)

That might be too much in the UI. If there were a way to show a help icon, I'd be totally happy to add these words to the help text. In addition, when #560 is solved, we won't need to emphasize that comments will be lost in the conversion.

**Comment by apreshill** [comment]
That makes sense- thanks!

**Pull request merged**
